이미지 업로드 기능 구현
minumsa/barbershop pull request #18
Opened 2023-10-23 08:54 UTC by minumsa

업로드 페이지에서 이미지도 함께 업로드 및 수정할 수 있게 만들겠습니다.

2023-10-23 09:45 UTC, lingo-apple requested changes

2023-10-23 09:45 UTC, lingo-apple commented on app/MainTab.tsx
> +    console.log(barbershops);
지우는걸 깜빡하신듯!

2023-10-23 09:45 UTC, lingo-apple commented on app/Upload.tsx
> +            // router.push("/admin");
아마 handleUpload 나 handleEdit 이 끝나고 `/admin` 으로 가고 싶었던거 같은데, 그렇다면
```
isUpload ? await handlUpload() : await handleEdit();
router.push("/admin");
```
같이 await 를 사용하면 될것 같아요.

2023-10-23 09:45 UTC, lingo-apple commented on app/lib/api.ts
> +  file: any,
수정할때도 UploadImage api 를 사용해야될것 같아요

2023-10-23 09:45 UTC, lingo-apple commented on app/Upload.tsx
> +  console.log("isUpload", isUpload);
여기도요!

2023-10-24 04:27 UTC, minumsa commented on app/Upload.tsx
> +  console.log("isUpload", isUpload);
수정 완료했습니다. 😄

2023-10-24 04:27 UTC, minumsa commented on app/lib/api.ts
> +  file: any,
수정 완료했습니다. 😄

2023-10-24 04:27 UTC, minumsa commented on app/Upload.tsx
> +            // router.push("/admin");
수정 완료했습니다. 😄

2023-10-24 04:27 UTC, minumsa commented on app/MainTab.tsx
> +    console.log(barbershops);
수정 완료했습니다. 😄

2023-10-24 04:33 UTC, lingo-apple approved these changes
👍

2023-10-24 04:33 UTC, merged